# Generated by Django 4.2.3 on 2023-07-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Назва продукту')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Ціна за одиницю продукту')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кількість купленого чи проданого продукту')),
                ('type_operation', models.CharField(choices=[('Купити', 'Купити'), ('Продати', 'Продати')], max_length=10, verbose_name='Дію з продуктом')),
                ('date_operation', models.DateTimeField(auto_now=True, verbose_name='Дата дії над продуктом')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс користувача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='declaration/', verbose_name='Файл декларації')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата та час завантаження декларації')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.personalaccount', verbose_name='Банківський рахунок')),
            ],
        ),
    ]
