# Generated by Django 4.2.3 on 2023-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Загальна кількість продукту'),
        ),
    ]
